### ISSUE TITLE
Licensing for django-adminlte2

### ISSUE THREAD

**Issue by suhailrehman** [adamcharnock/django-adminlte2#10]
Hello,

I'm interested in using this for an academic research project, I was just wondering what license this project is under. We're allowed to use any free license, but just want to make sure before we build out our dashboard around this.

Keep up the great work!

Suhail

**Comment by adamcharnock** [comment]
Hi @suhailrehman. My apologies, I was quite surprised the find the license file empty! I've just updated it. The license is MIT, which is a free license.

I hope the project goes well.
