### ISSUE TITLE
Header template crashes in Django 2.x

### ISSUE THREAD

**Issue by gbts** [adamcharnock/django-adminlte2#12]
Since `User.is_authenticated` is now a property in Django 2.x, the `is_authenticated()` call in `templatetags/adminlte_helpers.py` now raises an exception. There's PR #11 that removes the parentheses but it would break compatibility with <2.x, so something like

    user = context['request'].user if user is None else user
    authenticated = user.is_authenticated
    authenticated = authenticated() if callable(authenticated) else authenticated
    return 'https://www.gravatar.com/avatar/{hash}?s={size}&d=mm'.format(
        hash=md5(user.email.encode('utf-8')).hexdigest() if authenticated else '',
        size=size or '',
    )

should do the trick.

**Comment by adamcharnock** [comment]
Thanks for the report. I've just pushed a fix and release ``0.2.2``.
