### ISSUE TITLE
'bool' object is not callable

### ISSUE THREAD

**Issue by herzcthu** [adamcharnock/django-adminlte2#13]
I got the following error when trying to use adminlte admin.
`
Request Method: | GET
-- | --
http://127.0.0.1:8000/admin/
2.0
TypeError
'bool' object is not callable
/home/sithu/PycharmProjects/chatbot/venv/lib/python3.5/site-packages/django_adminlte/templatetags/adminlte_helpers.py in avatar_url, line 20
/home/sithu/PycharmProjects/chatbot/venv/bin/python
3.5.2
['/home/sithu/PycharmProjects/chatbot',  '/home/sithu/PycharmProjects/chatbot',  '/home/sithu/PycharmProjects/chatbot/share/pyshared',  '/home/sithu/PycharmProjects/chatbot/venv/lib/python35.zip',  '/home/sithu/PycharmProjects/chatbot/venv/lib/python3.5',  '/home/sithu/PycharmProjects/chatbot/venv/lib/python3.5/plat-x86_64-linux-gnu',  '/home/sithu/PycharmProjects/chatbot/venv/lib/python3.5/lib-dynload',  '/usr/lib/python3.5',  '/usr/lib/python3.5/plat-x86_64-linux-gnu',  '/home/sithu/PycharmProjects/chatbot/venv/lib/python3.5/site-packages',  '/home/sithu/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/173.3942.36/helpers/pycharm_matplotlib_backend']
`
as indicated in error message, it is cause by user.is_authenticated() method called in adminlte_helpers.py.
Instead of using method, if I change to user.is_authenticated and use as property it is working.

**Comment by adamcharnock** [comment]
Thanks for the report. I've just pushed a fix and release ``0.2.2``.

**Comment by cizaquita** [comment]
`File "C:\Program Files (x86)\Python36-32\lib\site-packages\django_adminlte\templatetags\adminlte_helpers.py", line 19, in avatar_url
    hash=md5(user.email.encode('utf-8')).hexdigest() if user.is_authenticated() else '',
TypeError: 'bool' object is not callable`

I'm having the same problem with the latest version, How can I fix it?

Thanks 🤗
