### ISSUE TITLE
Local copy of jquery-ui.min.js

### ISSUE THREAD

**Issue by clover-es** [adamcharnock/django-adminlte2#18]
Hi!

I was wondering if there was any specific reason to keep jquery-ui.min.js file as an external resource pointing to jquery.com domain. Given the fact that it's an specific release version (1.11.4), it wouldn't pass the keep up-to-date argument.

I'm developing an application using this django package that may go offline, so it would be interesting to have this a local resource.

Would you accept such modification?

Thank you,
Guillermo.

**Comment by gilsondev** [comment]
This is a good idea. What do you think @adamcharnock?

**Comment by adamcharnock** [comment]
Hi @clover-es and @gilsondev, sorry for the delay in replying. Yes, I think this is definitely a good idea. Happy to accept a pull request, in fact, I see #19 has been created already. Is that good to go?

**Comment by clover-es** [comment]
Should be good to go! Just ignore [last commit](https://github.com/adamcharnock/django-adminlte2/pull/19/commits/d0839e401a65b65d33364a8cb0e9fc28ec82a326) on that PR because it wasn't done on purpose.

**Comment by adamcharnock** [comment]
Merged! I've just release 0.3.0 for this change. Thank you very much for the PR!
