### ISSUE TITLE
Change the logo of AdminLTE in DjangoAdmin

### ISSUE THREAD

**Issue by padagoal** [adamcharnock/django-adminlte2#21]
How can I change the logo of AdminLTE, in the topLeft corner, to my own logo?, in the administrator of Django.

**Comment by apecnascimento** [comment]
you need to create "templates/adminlte/lib/_main_header.html" in your project and override the "block logo".

**Comment by adamcharnock** [comment]
Thank you for answering this @apecnascimento, you are absolutely right. I'll close this now.
