### ISSUE TITLE
NoReverseMatch: 'admin'

### ISSUE THREAD

**Issue by alexmndzdev** [adamcharnock/django-adminlte2#24]
When i'm trying to see the example in a view, is returning me this error :cry: 
`django.urls.exceptions.NoReverseMatch: 'admin' is not a registered namespace`

**Comment by alexmndzdev** [comment]
Okok, thankyou so much for the quick response, i just discovered that it was the cache of the browser, i don't know why but **Brave** is caching all, even when i do a clean reload, then i try in firefox and everything is ok!. I regret the inconvenience :sweat_smile:

**Comment by adamcharnock** [comment]
No worries @alexmndzdev! Let me know if you have any more problems, and feel free to submit pull requests 😀
